safe: true
lsi: false
paginate: 40
paginate_path: "blog/page:num"
url: 'http://altoros.github.io'
permalink: '/:year/:title'
pygments: true
markdown: rdiscount
plugins:
  - jekyll-redirect-from
rdiscount:
  extensions: [smart, autolink]
