safe: true
lsi: false
paginate: 4
paginate_path: "blog/page:num"
url: 'http://altoros.github.io'
permalink: '/:year/:title'
pygments: true
markdown: rdiscount
rdiscount:
  extensions: [smart, autolink]
